// @ts-nocheck
// This file was generated by specta. DO NOT EDIT.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * HTTP リクエストを実行する Tauri Command
 * 
 * フロントエンドから invoke("send_request", { req }) で呼び出される。
 * - HTTP の非 2xx ステータス（401, 404, 500 等）はエラー扱いにしない（Ok で返す）
 * - URL 不正、タイムアウト、ネットワーク断など「送信自体ができない」場合のみ Err
 */
async sendRequest(req: HttpRequest) : Promise<Result<HttpResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_request", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 新しい履歴エントリーを保存する Tauri Command
 * 
 * フロントエンドから invoke("save_history_entry", { entry }) で呼び出される。
 * - 新しいエントリーを配列の先頭に追加する（新しい順）
 * - MAX_HISTORY_ENTRIES を超えた場合は古いエントリーから削除する
 */
async saveHistoryEntry(entry: HistoryEntry) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_history_entry", { entry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 全履歴エントリーを取得する Tauri Command
 * 
 * フロントエンドから invoke("get_history") で呼び出される。
 * サイドバーの履歴一覧表示に使用する。
 * 新しい順（タイムスタンプ降順）で返す。
 */
async getHistory() : Promise<Result<HistoryEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 指定した ID の履歴エントリーを削除する Tauri Command
 * 
 * フロントエンドから invoke("delete_history_entry", { id }) で呼び出される。
 * サイドバーの履歴一覧で個別削除ボタンを押したときに使用する。
 */
async deleteHistoryEntry(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 全履歴を削除する Tauri Command
 * 
 * フロントエンドから invoke("clear_history") で呼び出される。
 * サイドバーの「全履歴削除」ボタンを押したときに使用する。
 */
async clearHistory() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 全コレクションを取得する Tauri Command
 * 
 * フロントエンドから invoke("get_collections") で呼び出される。
 * サイドバーのコレクションツリー表示に使用する。
 */
async getCollections() : Promise<Result<Collection[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * コレクション全体を上書き保存する Tauri Command
 * 
 * フロントエンドから invoke("save_collections", { collections }) で呼び出される。
 * コレクションの追加・削除・編集のたびに全体をまとめて保存する。
 * （個別操作の API を作るより、フロントエンドで state を管理して一括保存する方がシンプル）
 */
async saveCollections(collections: Collection[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_collections", { collections }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * フロントエンドに返す統一エラー型
 * Tauri Command の戻り値 Err として使用し、specta で TypeScript 型を自動生成する
 * thiserror::Error を derive して Display トレイトを自動実装（{message} を表示）
 */
export type AppError = { 
/**
 * エラーの種別コード（フロントエンドでエラー種別を判別するために使用）
 */
code: AppErrorCode; 
/**
 * UI に表示するユーザー向けエラーメッセージ（機密情報を含めない）
 */
message: string; 
/**
 * 開発中のデバッグ用詳細情報（ユーザーには表示しない前提）
 */
detail: string | null }
/**
 * エラーの種別を表す列挙型
 * フロントエンド側で switch/case で分岐するために使う
 */
export type AppErrorCode = "InvalidRequest" | "Network" | "Timeout" | "Io" | "Serialize" | "Unexpected"
/**
 * コレクション全体を表す構造体
 * 
 * トップレベルにリクエストとフォルダを含む。
 * 1 つのコレクション = 1 つの JSON ファイルとして保存される。
 */
export type Collection = { 
/**
 * 一意な識別子（UUID v4）
 */
id: string; 
/**
 * コレクションの表示名（例: "My API"）
 */
name: string; 
/**
 * トップレベルのリクエスト一覧（フォルダに属さないリクエスト）
 */
requests: SavedRequest[]; 
/**
 * トップレベルのフォルダ一覧
 */
folders: CollectionFolder[] }
/**
 * コレクション内のフォルダ（再帰的にネスト可能）
 * 
 * フォルダ内にリクエストとサブフォルダを含めることができる。
 * ツリー構造でリクエストを整理するために使う。
 */
export type CollectionFolder = { 
/**
 * 一意な識別子（UUID v4）
 */
id: string; 
/**
 * フォルダの表示名（例: "Users API"）
 */
name: string; 
/**
 * フォルダ内のリクエスト一覧
 */
requests: SavedRequest[]; 
/**
 * サブフォルダの一覧（再帰的にネスト可能）
 */
folders: CollectionFolder[] }
/**
 * リクエスト履歴の 1 エントリー
 * 
 * HTTP リクエストを送信するたびに 1 件ずつ作成される。
 * サイドバーの履歴一覧に表示し、クリックすると過去のリクエスト内容を復元できる。
 */
export type HistoryEntry = { 
/**
 * 一意な識別子（UUID v4 で生成。例: "550e8400-e29b-41d4-a716-446655440000"）
 */
id: string; 
/**
 * 使用した HTTP メソッド（GET / POST / PUT / PATCH / DELETE）
 */
method: HttpMethod; 
/**
 * リクエスト先の URL（例: "https://api.example.com/users"）
 */
url: string; 
/**
 * 送信したカスタムヘッダー一覧（Key-Value ペア）
 */
headers: KeyValue[]; 
/**
 * 送信したリクエストボディ（None = ボディなし）
 */
body: RequestBody | null; 
/**
 * レスポンスの HTTP ステータスコード（例: 200, 404）
 * リクエスト送信に失敗した場合は None
 */
status: number | null; 
/**
 * リクエスト〜レスポンスの所要時間（ミリ秒）
 * リクエスト送信に失敗した場合は None
 */
elapsed_ms: number | null; 
/**
 * 履歴を記録した日時（ISO 8601 形式の文字列。例: "2026-03-04T15:30:00+09:00"）
 * chrono::Local::now() で生成し、to_rfc3339() で文字列化する
 */
timestamp: string }
/**
 * HTTP メソッドの列挙型
 * フロントエンドのドロップダウンで選択される値と対応する
 */
export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE"
/**
 * フロントエンドから Tauri Command に渡すリクエスト情報
 * send_request コマンドの引数として使用する
 */
export type HttpRequest = { method: HttpMethod; url: string; headers: KeyValue[]; body: RequestBody | null; timeout_ms: number | null }
/**
 * Tauri Command からフロントエンドに返すレスポンス情報
 * HTTP ステータスが 4xx/5xx でもエラーにせず、この構造体に格納して返す
 */
export type HttpResponse = { status: number; headers: ResponseKeyValue[]; body: string; elapsed_ms: number; size_bytes: number }
/**
 * ヘッダーやクエリパラメータなど、Key-Value ペアを表す汎用構造体
 * enabled フラグで一時的に無効化できる（UI でチェックボックスを OFF にした状態）
 */
export type KeyValue = { key: string; value: string; enabled: boolean }
/**
 * リクエストボディの種別
 * UI の「Body 種別」切り替え（JSON / Text）に対応する
 */
export type RequestBody = 
/**
 * プレーンテキストとして送信する（Content-Type: text/plain）
 */
{ Text: { content: string } } | 
/**
 * JSON として送信する（Content-Type: application/json）
 */
{ Json: { content: string } }
/**
 * レスポンスヘッダーの Key-Value ペア
 * リクエスト側の KeyValue と異なり enabled フラグは不要
 */
export type ResponseKeyValue = { key: string; value: string }
/**
 * コレクション内に保存されたリクエスト情報
 * 
 * 履歴エントリー（HistoryEntry）と異なり、レスポンス情報（status / elapsed_ms）は含まない。
 * ユーザーが「コレクションに保存」操作をしたときに作成される。
 */
export type SavedRequest = { 
/**
 * 一意な識別子（UUID v4）
 */
id: string; 
/**
 * リクエストの表示名（例: "ユーザー一覧取得"）
 */
name: string; 
/**
 * HTTP メソッド
 */
method: HttpMethod; 
/**
 * リクエスト先の URL
 */
url: string; 
/**
 * カスタムヘッダー一覧
 */
headers: KeyValue[]; 
/**
 * リクエストボディ（None = ボディなし）
 */
body: RequestBody | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
