// ─── モジュール宣言 ───
mod commands; // Tauri Command（フロントエンドから呼び出す API）
mod error;    // AppResult / AppError 統一エラー型
mod types;    // HTTP DTO（HttpRequest, HttpResponse 等）

// tracing ログ基盤に必要なインポート
use tracing_subscriber::{fmt, EnvFilter};

/// アプリケーションのメインエントリーポイント
/// モバイル向けビルド時は tauri::mobile_entry_point として動作する
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // ─── tracing ログ基盤の初期化 ───
    // RUST_LOG 環境変数が設定されていればそのレベルを使い、未設定なら info レベルにする
    fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_target(true) // ログ出力にモジュールパス（ターゲット）を含める
        .init();

    // ─── tauri-specta ビルダーの構築 ───
    // フロントエンドから呼び出せる Tauri Command を登録する
    // specta がここに登録された Command から TypeScript 型を自動生成する
    let builder = tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::http::send_request,          // HTTP リクエスト送信コマンド
            commands::history::save_history_entry,  // 履歴エントリーの保存（Phase 3）
            commands::history::get_history,          // 全履歴の取得（Phase 3）
            commands::history::delete_history_entry, // 履歴エントリーの削除（Phase 3）
            commands::history::clear_history,        // 全履歴の削除（Phase 3）
            commands::collection::get_collections,   // 全コレクションの取得（Phase 4）
            commands::collection::save_collections,  // コレクションの保存（Phase 4）
        ]);

    // ─── 開発時のみ TypeScript 型定義を自動生成 ───
    // debug ビルドのときだけ src/lib/bindings.ts を出力する
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                // Rust の u64 等を TypeScript の number として出力する（BigInt にしない）
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                // 生成ファイルの先頭に付けるヘッダーコメント
                .header("// @ts-nocheck\n// This file was generated by specta. DO NOT EDIT.\n"),
            // 出力先: src-tauri/ からの相対パスで src/lib/bindings.ts を指す
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    // ─── Tauri アプリケーションの構築・起動 ───
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init()) // ファイル・URL オープン用プラグイン
        .invoke_handler(builder.invoke_handler()) // specta ビルダーから invoke ハンドラーを生成
        .setup(move |app| {
            builder.mount_events(app); // specta のイベントをアプリにマウント
            Ok(())
        })
        .run(tauri::generate_context!()) // tauri.conf.json を読み込んでアプリを実行
        .expect("error while running tauri application");
}

